<a href="https://colab.research.google.com/github/sairam178/Foundation-of-machine-learning/blob/main/exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [111]:
import numpy as np


In [112]:
cost_price = np.array([1500,3000,5000])

In [113]:
print(cost_price.shape)
print(cost_price.ndim)

(3,)
1


In [114]:
daily_sales = np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])

In [115]:
print(daily_sales.shape)
print(daily_sales.ndim)


(3, 4)
2


In [116]:
result = daily_sales+2
print(result)
print(np.sum(result,axis=0))

[[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]
[23 31 20 28]


In [117]:
result = np.dot(cost_price,daily_sales)
print(result)
print(np.sqrt(daily_sales))

[40000 58500 34000 56000]
[[3.16227766 3.87298335 2.82842712 3.46410162]
 [2.23606798 2.64575131 2.         2.44948974]
 [1.41421356 1.73205081 1.41421356 2.        ]]


In [118]:
print(daily_sales[1])

[5 7 4 6]


In [119]:
print(daily_sales[:,0:2])

[[10 15]
 [ 5  7]
 [ 2  3]]


In [120]:
print(daily_sales.reshape(1,12))

[[10 15  8 12  5  7  4  6  2  3  2  4]]


In [121]:
print(daily_sales.reshape(2,6))

[[10 15  8 12  5  7]
 [ 4  6  2  3  2  4]]


In [122]:
predict_sales = np.random.randint(daily_sales.min(),daily_sales.max(),size=(3,4))
print(predict_sales)

[[ 5  5 11 13]
 [ 4  9  5 12]
 [10 13  7 13]]


In [123]:
print(np.random.rand(5))

[0.97091795 0.94693526 0.38524211 0.9563664  0.81258995]


In [124]:
print(np.sum(predict_sales))
print(np.sum(predict_sales,axis=0))
print(np.sum(predict_sales,axis=1))

107
[19 27 23 38]
[34 30 43]


In [125]:
marks = np.array([[78,85,90],[45,60,55],[88,90,95],[30,40,45],[65,70,75]])
print(marks)

[[78 85 90]
 [45 60 55]
 [88 90 95]
 [30 40 45]
 [65 70 75]]


In [126]:
print(marks.shape)
print(marks.size)
print(marks.ndim)
print(marks.dtype)

(5, 3)
15
2
int64


In [127]:
print(marks[1:2])

[[45 60 55]]


In [128]:
print(marks[:,2])

[90 55 95 45 75]


In [129]:
print(marks[0,1])

85


In [130]:
print(np.mean(marks,axis =0))
print(np.mean(marks,axis =1))


[61.2 69.  72. ]
[84.33333333 53.33333333 91.         38.33333333 70.        ]


In [131]:
print(marks>=80)

[[False  True  True]
 [False False False]
 [ True  True  True]
 [False False False]
 [False False False]]


In [132]:
marks +=5
print(marks)

[[ 83  90  95]
 [ 50  65  60]
 [ 93  95 100]
 [ 35  45  50]
 [ 70  75  80]]


In [133]:
mark = np.where(marks>=50,"1","0")
print(mark)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']
 ['0' '0' '1']
 ['1' '1' '1']]


In [134]:
mark = np.where(marks<=40,0,marks)
print(mark)

[[ 83  90  95]
 [ 50  65  60]
 [ 93  95 100]
 [  0  45  50]
 [ 70  75  80]]


In [135]:
avg = np.mean(marks,axis=1)
print(avg)

[89.33333333 58.33333333 96.         43.33333333 75.        ]


In [136]:
Grades = np.where(avg>=85,'A',np.where(avg>=70,'B',np.where(avg>=50,'C','0')))
print(Grades)

['A' 'C' 'A' '0' 'B']


In [142]:
backup = marks.copy()
marks[0,0]=0
print(backup)
print(marks)

[[ 83  90  95]
 [ 50  65  60]
 [ 93  95 100]
 [ 35  45  50]
 [ 70  75  80]]
[[  0  90  95]
 [ 50  65  60]
 [ 93  95 100]
 [ 35  45  50]
 [ 70  75  80]]
