<a href="https://colab.research.google.com/github/sairam178/Foundation-of-machine-learning/blob/main/exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
cost_price = np.array([1500,3000,5000])

In [ ]:
print(cost_price.shape)
print(cost_price.ndim)

NameError: name 'cost_price' is not defined

In [ ]:
daily_sales = np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])

NameError: name 'np' is not defined

In [ ]:
print(daily_sales.shape)
print(daily_sales.ndim)


NameError: name 'daily_sales' is not defined

In [ ]:
result = daily_sales+2
print(result)
print(np.sum(result,axis=0))

[[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]
[23 31 20 28]


In [ ]:
result = np.dot(cost_price,daily_sales)
print(result)
print(np.sqrt(daily_sales))

[40000 58500 34000 56000]
[[3.16227766 3.87298335 2.82842712 3.46410162]
 [2.23606798 2.64575131 2.         2.44948974]
 [1.41421356 1.73205081 1.41421356 2.        ]]


In [ ]:
print(daily_sales[1])

[5 7 4 6]


In [ ]:
print(daily_sales[:,0:2])

[[10 15]
 [ 5  7]
 [ 2  3]]


In [ ]:
print(daily_sales.reshape(1,12))

[[10 15  8 12  5  7  4  6  2  3  2  4]]


In [ ]:
print(daily_sales.reshape(2,6))

[[10 15  8 12  5  7]
 [ 4  6  2  3  2  4]]


In [ ]:
predict_sales = np.random.randint(daily_sales.min(),daily_sales.max(),size=(3,4))
print(predict_sales)

[[ 4  3 13 10]
 [12 11  6  3]
 [ 5  8  6  9]]


In [ ]:
print(np.random.rand(5))

[0.09062303 0.98545624 0.05514435 0.06636752 0.29146607]


In [ ]:
print(np.sum(predict_sales))
print(np.sum(predict_sales,axis=0))
print(np.sum(predict_sales,axis=1))

90
[21 22 25 22]
[30 32 28]


In [ ]:
marks = np.array([[78,85,90],[45,60,55],[88,90,95],[30,40,45],[65,70,75]])
print(marks)

[[78 85 90]
 [45 60 55]
 [88 90 95]
 [30 40 45]
 [65 70 75]]


In [ ]:
print(marks.shape)
print(marks.size)
print(marks.ndim)
print(marks.dtype)

(5, 3)
15
2
int64


In [ ]:
print(marks[1:2])

[[45 60 55]]


In [ ]:
print(marks[:,2])

[90 55 95 45 75]


In [ ]:
print(marks[0,1])

85


In [ ]:
print(np.mean(marks,axis =0))
print(np.mean(marks,axis =1))


[61.2 69.  72. ]
[84.33333333 53.33333333 91.         38.33333333 70.        ]


In [ ]:
print(marks>=80)

[[False  True  True]
 [False False False]
 [ True  True  True]
 [False False False]
 [False False False]]


In [ ]:
marks +=5
print(marks)

[[ 83  90  95]
 [ 50  65  60]
 [ 93  95 100]
 [ 35  45  50]
 [ 70  75  80]]


In [ ]:
mark = np.where(marks>=50,"1","0")
print(mark)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']
 ['0' '0' '1']
 ['1' '1' '1']]


In [ ]:
mark = np.where(marks<=40,0,marks)
print(mark)

[[ 83  90  95]
 [ 50  65  60]
 [ 93  95 100]
 [  0  45  50]
 [ 70  75  80]]


In [ ]:
avg = np.mean(marks,axis=1)
print(avg)

[89.33333333 58.33333333 96.         43.33333333 75.        ]


In [ ]:
Grades = np.where(avg>=85,'A',np.where(avg>=70,'B',np.where(avg>=50,'C','0')))
print(Grades)

['A' 'C' 'A' '0' 'B']


In [ ]:
backup = marks.copy()
marks[0,0]=0
print(backup)
print(marks)

[[ 83  90  95]
 [ 50  65  60]
 [ 93  95 100]
 [ 35  45  50]
 [ 70  75  80]]
[[  0  90  95]
 [ 50  65  60]
 [ 93  95 100]
 [ 35  45  50]
 [ 70  75  80]]


In [ ]:
electricity = np.random.randint(120,650,size=(4,7))
print(electricity)
print(electricity.shape)
print(electricity.size)
print(electricity.ndim)
print(electricity.dtype)

[[267 643 630 576 283 591 599]
 [252 239 578 487 317 287 389]
 [436 341 326 255 627 131 499]
 [212 623 225 361 501 502 529]]
(4, 7)
28
2
int64


In [ ]:
import numpy as np
electricity = np.random.randint(120,650,size=(4,7))
print(electricity)
print(electricity.shape)
print(electricity.size)
print(electricity.ndim)
print(electricity.dtype)
average_usage_per_hostel = np.mean(electricity, axis=1)
print("Average electricity usage per hostel:")
print(average_usage_per_hostel)

[[182 128 637 357 427 598 583]
 [127 366 613 419 332 189 464]
 [518 537 174 512 462 140 150]
 [425 421 153 554 228 162 346]]
(4, 7)
28
2
int64
Average electricity usage per hostel:
[416.         358.57142857 356.14285714 327.        ]


In [ ]:
maximum_usage_per_hostel = np.max(electricity, axis=1)
print("Maximum electricity usage per hostel:")
print(maximum_usage_per_hostel)

Maximum electricity usage per hostel:
[637 613 537 554]


In [ ]:
highest_avg_usage_hostel_index = np.argmax(average_usage_per_hostel)
highest_avg_usage_hostel_number = highest_avg_usage_hostel_index + 1
highest_avg_usage_value = average_usage_per_hostel[highest_avg_usage_hostel_index]

print(f"Hostel with the highest average electricity usage: Hostel {highest_avg_usage_hostel_number}")
print(f"Average usage for this hostel: {highest_avg_usage_value:.2f}")

Hostel with the highest average electricity usage: Hostel 1
Average usage for this hostel: 416.00


In [ ]:
print(np.where(electricity>550,electricity*1.20,electricity))


[[182.  128.  764.4 357.  427.  717.6 699.6]
 [127.  366.  735.6 419.  332.  189.  464. ]
 [518.  537.  174.  512.  462.  140.  150. ]
 [425.  421.  153.  664.8 228.  162.  346. ]]


In [ ]:
week_avg=electricity.mean(axis=0)
above_avg=electricity>week_avg
print(above_avg)

NameError: name 'electricity' is not defined