In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np


In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Array properties

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

In [ ]:
# @title Default title text
print(arr.shape)#rows and columns
print(arr.size) # total elements
print(arr.ndim) # diminesion
print(arr.dtype) #

(2, 3)
6
2
int64


Data types


In [ ]:
arr = np.array([1,2,3])
print(arr.dtype)

int64


type conversion

In [ ]:
arr = np.array([1.2,2.5,3.7])
arr_int = arr.astype(int)
print(arr_int)

[1 2 3]


indexing and slicing

In [ ]:
arr = np.array([1,2,3,])

print(arr[0])
print(arr[-1])

1
3


1D Slicing


In [ ]:
print(arr[1:3])
print(arr[:2])
print(arr[::2])

[2 3]
[1 2]
[1 3]


2D - Indexing


In [ ]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat[0,1])
print(mat[1])

2
[4 5 6]


In [ ]:
print(mat[:,1]) # fetch the columun

[2 5 8]


In [ ]:
a= np.array([1,2,3])
b=a;
b[0]=99;#not safe beacuse it changes the a array also
print(a)
print(b)



#copy command

a=np.array([2,3,4])
b=a.copy();
b[0]=99;
print("a: ",a)
print("b: ",b)


[99  2  3]
[99  2  3]
a:  [2 3 4]
b:  [99  3  4]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a*b)
print(a/b)
print(a-b)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[-3 -3 -3]


Scalar operations


In [ ]:
print(a+2)
print(a*2)
print(a/2)
print(a-2)

[3 4 5]
[2 4 6]
[0.5 1.  1.5]
[-1  0  1]


unfus(universal functions)

In [ ]:
arr= np.array([1,4,9,16])

print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.max(arr))
print(np.min(arr))
print(np.sin(arr))
print(np.cos(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))


[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
16
1
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948]
7.5
6.5
5.678908345800274
32.25


Boolean Indexing

In [ ]:
arr = np.array([10,20,30,40,50])
print(arr[arr>25])
print(arr>25)

[30 40 50]
[False False  True  True  True]


Broadcasting Rule

In [ ]:
arr = np.array([1,2,3,])
print(arr+10)

[11 12 13]


In [ ]:
mat = np.array([[1,2,3],[4,5,6]])
print(mat+10)

[[11 12 13]
 [14 15 16]]


In [ ]:
row = np.array([1,2,3])
print(mat+row)

[[2 4 6]
 [5 7 9]]


**Matrix Mulitiplication**

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(np.dot(A,B))

[[19 22]
 [43 50]]


In [ ]:
print(A.T)

[[1 3]
 [2 4]]


Random Module

In [ ]:
np.random.rand(5)


array([0.17980722, 0.04586975, 0.12833563, 0.2235234 , 0.52758416])

In [ ]:
np.random.rand(3,3)

array([[0.3250157 , 0.45184758, 0.19721981],
       [0.34749748, 0.48469635, 0.98308436],
       [0.15668554, 0.74772324, 0.02379625]])

In [ ]:
np.random.randint(1,100,17)#(start,ending,no of values)


array([54, 85, 79, 17, 33, 34,  2, 73, 71, 14, 44, 38, 38, 19, 12, 28, 74])

**Reshaping arrays**

In [ ]:
arr = np.arange(12)
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Axis in Numpy


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(np.sum(arr))

21


In [ ]:
print(np.sum(arr,axis=0))  #column wise

[5 7 9]


In [ ]:
print(np.sum(arr,axis=1))  # row wise

[ 6 15]


Where is numpy


In [ ]:
 arr = np.array([1,2,3,4,5])
 print(np.where(arr>2))

(array([2, 3, 4]),)


In [ ]:
arr = np.array([1,-5,3,4,5])

In [ ]:
result = np.where(arr < 0,0,arr)
print(result)

[1 0 3 4 5]


In [ ]:
result = np.where(arr%2!=0,-1,arr)
print(result)

[-1 -1 -1  4 -1]


In [ ]:
marks =np.array([45,76,29,96])
status= np.where(marks>=50,1,0)
print(status)

[0 1 0 1]


In [ ]:
data = np.array([590,509905,50950,59095])

In [ ]:
mean_val = np.mean(data)
result = np.where(data>mean_val,mean_val,data)
print(result)

[   590. 155135.  50950.  59095.]


Aplying (where) condition in 2d array

In [ ]:
mat  = np.array([[10,23,4,5],[93,299,499,29]])

In [ ]:
result = np.where(mat>=50,1,0)
print(result)

[[0 0 0 0]
 [1 1 1 0]]
